### ISSUE TITLE
Alarm Time input field is white text on white background

### ISSUE THREAD

**Issue by michaelherger** [AF-1/lms-darkdefaultskin#2]
Go to Settings/Player Alarm. The alarm time input field seems to be empty. But it's white on white.

![Bildschirm­foto 2023-02-19 um 22 12 37](https://user-images.githubusercontent.com/2789989/219975512-248d2731-202f-4120-8763-7af483abcfb4.png)

**Comment by AF-1** [comment]
Didn't even get a notification (email) for this issue, strange...
Anyway, should be fixed in 0.1.6. Thanks for letting me know.

**Comment by michaelherger** [comment]
Running from a git clone I can confirm this is fixed. Thanks!
