### ISSUE TITLE
CSS skin for LMS

### ISSUE THREAD

**Issue by lovehifi** [AF-1/lms-darkdefaultskin#4]
Hello AF,

I've edited "slimserver.css" to modify the LMS interface slightly and published it on the forum (https://forums.slimdevices.com/forum/user-forums/general-discussion/1650207-lms-mod-skin-and-35-radios-playlists).

Afterwards, I received a suggestion to turn it into a plugin. While researching how to create a plugin, I discovered your DarkDefaultSkin plugin. I proceeded by using the "skin.css" from your plugin to adapt the CSS changes I made.

Honestly, upon seeing the DarkDefaultSkin plugin, I didn't intend to create a similar plugin with just color differences.

If possible, could you integrate what I've done into your plugin? Or perhaps enhance them, such as using the cover of the currently playing music as the background when playing, or allowing users to set their own background through interface settings... Or any other enhancements.

Thank you.

**Comment by AF-1** [comment]
I'd actually thought about letting users set a custom background image in LMS settings. But it's not that easy:
the tricky part is to get LMS to load dynamically changing CSS values that override the values in `slimserver.css` and `skin.css`. Adding a bit of simple JS is probably not going to accomplish this. It would most likely require modifying the LMS Ext JS Library or other LMS JS files. Unfortunately, I'm not very familiar with those.

The next best thing you can do is this: enable users to use a  background image by placing a background image with **hard-coded** name in a special folder (see [bgimage branch](https://github.com/AF-1/lms-darkdefaultskin/tree/bgimage)).
